extends:
   - 'airbnb-base'
 env:
   node: true
   browser: true
   jest: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:flowtype/recommended'

rules:
no-console: 0
